stages:
  - build
  - deploy
  
# build-job:
#   tags:
#     - 410silver
#   stage: build
#   script:
#     - echo "listing files"
#     - ls -l
    
#   only:
#     - master
#     - developer

deploy-job:
  tags:
    - 410silver
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$RSYNC_KEY")
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - ssh nmendoza@atria.cs.odu.edu
    # - rsync -auvz -e "ssh" ./index.html nmendoza@atria.cs.odu.edu:public/
    
    # - ls
    # - cat ~/.ssh/
    # - rsync -auvz -e "ssh" ./index.html nmendoza@atria.cs.odu.edu:public/
    # - ssh-agent -k
  only:
    - master
    - developer