stages:
  - build
  - deploy
  
# build-job:
#   tags:
#     - 410silver
#   stage: build
#   script:
#     - echo "listing files"
#     - ls -l
    
#   only:
#     - master
#     - developer

deploy-job:
  tags:
    - 410silver
  stage: deploy
  script:
    - apt-get update
    - apt-get --yes --force-yes install git
    - git submodule update --init --recursive
    # - eval $(ssh-agent -s)
    # - ssh-add <(echo "$RSYNC_KEY")
    # - ls
    # - cat ~/.ssh/
    # - rsync -auvz -e "ssh" ./index.html nmendoza@atria.cs.odu.edu:public/
    # - ssh-agent -k
  only:
    - master
    - developer