stages:
  - build
  - deploy
  
build-job:
  tags:
    - 410silver #No need to update this tag
  stage: build
  script:
    - echo "transferring files"
    - eval $(ssh-agent -t 5m -s)
    - ssh-add <(echo "$RSYNC_KEY") #Key must be updated
    - rsync -auvz -e ssh ./website/* 411silver@atria.cs.odu.edu:./
    - ssh-agent -k
  only:
    - master
