stages:
  - build
  - deploy
  
build-job:
  tags:
    - 410silver
  stage: build
  script:
    - echo "transferring files"
    - eval $(ssh-agent -t 5m -s)
    - ssh-add <(echo "$RSYNC_KEY")
    - rsync -auvz -e ssh ./website/* 410silver@atria.cs.odu.edu:./
    - ssh-agent -k
  only:
    - master

# deploy-job:
#   tags:
#     - "placeholder"
#   stage: deploy
#   script:
#     - eval $(ssh-agent -t 5m -s)
#     - ssh-add <(echo "$RSYNC_KEY")
#     - rsync -auvz -e "ssh" ./index.html 410silver@atria.cs.odu.edu:public_html/
#     - ssh-agent -k
#   only:
#     - master
