stages:
  - build
  - deploy
  
build-job:
  tags:
    - 410silver
  stage: build
  script:
    - echo "listing files"
    - ls -l
    
  only:
    - master
    - developer

deploy-job:
  tags:
    - 410silver
  stage: deploy
  script:
    - eval $(ssh-agent -t 5m -s)
    - ssh-add <(echo "$RSYNC_KEY")
    - rsync -auvz -e "ssh" ./index.html nmendoza@atria.cs.odu.edu:./public/
    - ssh-agent -k
  only:
    - master
    - developer